name: Unity C# Tests

on: [push]

jobs:
  test-csharp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x  # Используем актуальную версию .NET

      - name: Restore dependencies
        run: dotnet restore pon.sln

      - name: Build C# scripts
        run: dotnet build --no-restore --configuration Release

      - name: Run C# tests
        run: dotnet test --no-build --verbosity normal
